---
abstract: 'Provides a Perl interface to the MediaWiki API (https://www.mediawiki.org/wiki/API)'
author:
  - 'Jools Wills <buzz@exotica.org.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MediaWiki-API
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Encode: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Test::More: '0.98'
version: '0.52'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
